compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    spec: clang@8.1.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/local/clang-5.0.0/bin/clang
      cxx: /usr/local/clang-5.0.0/bin/clang++
      f77: /usr/bin/gfortran-4.9
      fc: /usr/bin/gfortran-4.9
    spec: clang@5.0.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-4.9
      cxx: /usr/bin/g++-4.9
      f77: /usr/bin/gfortran-4.9
      fc: /usr/bin/gfortran-4.9
    spec: gcc@4.9.4
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-6
      cxx: /usr/bin/g++-6
      f77: /usr/bin/gfortran-6
      fc: /usr/bin/gfortran-6
    spec: gcc@6.3.0
    target: x86_64
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: ubuntu14.04
    paths:
      cc: /usr/bin/gcc-7
      cxx: /usr/bin/g++-7
      f77: /usr/bin/gfortran-7
      fc: /usr/bin/gfortran-7
    spec: gcc@7.2.0
    target: x86_64
