language: python

branches:
  only:
  - wheels

env:
  global:
    # (1,2) Skip building for Python 2.7 on all platforms
    - CIBW_SKIP="cp27-* pp27-*"
    # Install dependencies on Linux and OSX
    - CIBW_BEFORE_BUILD="bash -x .github/library_builders.sh"
    # CMake shall search for static dependencies of HDF5 and ADIOS1
    - HDF5_USE_STATIC_LIBRARIES="ON"
    - ADIOS_USE_STATIC_LIBS="ON"

jobs:
  include:
    # perform a linux ARMv8 build
    # blocked by https://github.com/ornladios/ADIOS2/issues/2137
    # - services: docker
    #   arch: aarch64

    # perform a linux PPC64LE build
    # blocked by https://github.com/pypa/auditwheel/issues/36
    #            https://github.com/pypa/auditwheel/pull/213
    # - services: docker
    #   arch: ppc64le

    # perform a linux S390X build
    # blocked by https://github.com/GTkorvo/dill/issues/15
    # - services: docker
    #   arch: s390x

    # and a build for old macOS versions (10.13 with xcode9.4.1 ~2017)
    - os: osx
      osx_image: xcode9.4
      language: shell
      python: 3.6

install:
  - git clone --branch 0.11.1-alpha --depth 1 https://github.com/openPMD/openPMD-api.git src
  - cp library_builders.sh src/.github/
  - python3 -m pip install cibuildwheel==1.3.0

script:
  - cd src
  - python3 -m cibuildwheel --output-dir ../wheelhouse

after_success:
  - if [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
        python3 -m pip install -U twine;
        python3 -m twine upload --skip-existing wheelhouse/*;
    fi
