name: source

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Non-ASCII Characters
      run: .github/workflows/source/hasNonASCII
    - name: TABs
      run: .github/workflows/source/hasTabs
    - name: End-of-Line whitespaces
      run: .github/workflows/source/hasEOLwhiteSpace
    - name: PEP8
      run: |
        python3 -m pip install -U flake8
        python3 -m flake8 --exclude=thirdParty .

  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pyflakes
      run: |
        python3 -m pip install -U pyflakes
        python3 -m pyflakes docs/ examples/ test/ setup.py

  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: sudo apt-get install -y --no-install-recommends doxygen
    - name: Doxygen
      run: .github/workflows/source/buildDoxygen
